version: "3.9"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: springio/gs-spring-boot-docker2
    ports:
      - 8080:8080
    links:
      - api-database
